parameters:
    usps_api.zipcode_lookup.class: USPS\USPSZipCodeLookup
    usps_api.city_state_lookup.class: USPS\USPSCityStateLookup
    usps_api.rate_lookup.class: USPS\USPSRateLookup

services:
    usps_api.zipcode_lookup:
        class:      %usps_api.zipcode_lookup.class%
        calls:
            - [ setUsername, [ %usps_api.username% ] ]
            - [ setTestMode, [ %usps_api.testMode% ] ]
